[theme]
base = "light"
primaryColor = "#FF9800"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F5F5F5"
textColor = "#333333"

[server]
headless = true
port = 8501

[browser]
gatherUsageStats = false
